import type { Metadata } from "next";
import localFont from "next/font/local";
import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";
import StickyBlurHeader from "@/components/sticky-blur-header";
import { DynamicContextProvider } from "@dynamic-labs/sdk-react-core";
import { EthereumWalletConnectors } from "@dynamic-labs/ethereum";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<DynamicContextProvider
						settings={{
							environmentId: '073ce37c-55ce-467a-b97e-dca13b678ae8',
							walletConnectors: [EthereumWalletConnectors],
						}}>
						<div className="min-h-screen">
							<StickyBlurHeader />
							<main
								className="mt-4"
							>
								{children}
							</main>
						</div>
					</DynamicContextProvider>
				</ThemeProvider>
			</body>
		</html>
	);
}
